networks:
  pulse:
    name: pulse
services:
  database:
    image: postgres:17.9-alpine
    container_name: incident-db
    ports:
      - "5432:5432" 
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
          - pulse
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
        - pulse
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pulse

  alert-ingestion:
    build: ./services/alert-ingestion
    container_name: alert-ingestion
    ports:
      - "8001:8001"
    networks:
      - pulse
    depends_on:
      - database

  incident-management :
    build: ./services/incident-management
    container_name: incident-management
    networks:
      - pulse
    depends_on:
      - database
      - alert-ingestion

volumes:
  db-data:
  grafana_data:
  prometheus-data:
