services:
  database:
    image: postgres:17.9-alpine
    container_name: incident-db
    ports:
      - "5432:5432" 
    env_file:
      - .env  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - pulse

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - pulse
    env_file:
      - .env  


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pulse

  alert-ingestion:
    build: ./services/alert-ingestion
    container_name: alert-ingestion
    ports:
      - "8001:8001"
    networks:
      - pulse
    depends_on:
      database:
        condition: service_healthy

  incident-management:
    build: ./services/incident-management
    container_name: incident-management
    env_file:
      - ./services/incident-management/.env
    ports:
      - "8002:8002"
    networks:
      - pulse
    depends_on:
      database:
        condition: service_healthy
      alert-ingestion:
        condition: service_started

  on-call-service:
    build: ./services/on-call-service
    container_name: on-call-service
    env_file:
      - ./services/on-call-service/.env
    ports:
      - "8003:8003"
    networks:
      - pulse
    depends_on:
      database:
        condition: service_healthy
      incident-management:
        condition: service_started
  web-ui:
    build: ./services/web-ui
    container_name: web-ui
    ports:
      - "300:80"
    networks:
      - pulse


volumes:
  db-data:
  grafana_data:
  prometheus-data:

networks:
  pulse:
    name: pulse
